<?php
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n";
echo "<head>\n";
echo "<meta http-equiv=\"content-language\" content=\"zh-hk\">\n";
echo "<meta http-equiv=\"content-style-type\" content=\"text/css\">\n";
echo "<meta http-equiv=\"content-script-type\" content=\"text/javascript\">	<meta name=\"author\" content=\"學車課程專家MEG\">\n";
echo "<meta name=\"copyright\" CONTENT=\"Copyright © 2015 MEG Ltd. All Rights Reserved\">\n";
echo "<meta name=\"description\" content=\"獨家代理香港駕駛學院及A1駕駛學校等優質駕駛課程，唯一提供全港所有考線的一站式考牌學車顧問，滿足你的學車需要。\">\n";
echo "<meta name=\"keywords\" content=\"MEG,學車,私家車,輕型貨車,電單車,學車顧問,駕駛學院,A1,駕駛學校\">\n";
echo "<meta property=\"og:title\" content=\"MEG一站式學車平台 - 專業考牌學車顧問\" />\n";
echo "<meta property=\"og:site_name\" content=\"MEG一站式學車平台 - 專業考牌學車顧問\" />\n";
echo "<meta property=\"og:image\" content=\"http://www.meg.com.hk/images/logo_4.jpg\" />\n";
echo "<meta property=\"og:url\" content=\"http://www.meg.com.hk/tc/index.html\" />\n";
echo "<meta property=\"og:description\" content=\"獨家代理香港駕駛學院、自由學駕駛學校及A1駕駛學校等優質駕駛課程，唯一提供全港所有考線的一站式考牌學車顧問，滿足你的學車需要。\" />\n";
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n";
echo "<link rel=\"shortcut icon\" href=\"../images/favicon_3.ico\">\n";
echo "<title>MEG一站式學車平台 - 專業考牌學車顧問</title>\n";
echo "<!-- ** CSS ** -->\n";
echo "<link href=\"../css/common.css\" rel=\"stylesheet\">\n";
echo "<link href=\"../css/btn2.css\" rel=\"stylesheet\">\n";
echo "<link href=\"../css/style.css\" rel=\"stylesheet\">\n";
echo "<link href=\"../css/meg.css\" rel=\"stylesheet\">\n";
echo "<!link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\n";
echo "<!--slider-->\n";
echo "<link rel=\"stylesheet\" href=\"../imageslidermaker/ism/css/my-slider.css\"/>\n";
echo "<script src=\"../imageslidermaker/ism/js/ism-2.1.js\"></script>\n";
echo "</head>\n";
echo "<body id=\"meg\">\n";
echo "<div id=\"header_area\"><div class=\"inner clearfix\">\n";
echo "<!--<div id=\"MyBlog\">\n";
echo "<a href=\"http://www.meg.com.hk/promo/payment.html\" target=\"_blank\" ><img src=\"./images/banner.png\"</a>\n";
echo "</div>-->\n";
echo "	<div class=\"logo\"><a id=\"index_s\"><img src=\"../images/logo_2.png\"></a></div>\n";
echo "    <div class=\"social\">\n";
echo "        <ul>\n";
echo "		  <li><a href=\"https://www.facebook.com/meglimited\" target=\"_blank\"><img src=\"../images/social/social_fb_icon.png\"></a> </li>\n";
echo "          <li><a href=\"https://www.instagram.com/meg_driving/\" target=\"_blank\"><img src=\"../images/social/social_instagram_icon.png\"></a> </li>\n";
echo "          <li><a href=\"https://play.google.com/store/apps/details?id=hk.meg.android\" target=\"_blank\"><img src=\"../images/social/social_googleplay_icon.png\"></a> </li>\n";
echo "          <li><a href=\"https://itunes.apple.com/hk/app/xue-cheno.1/id416072313?mt=8\" target=\"_blank\"><img src=\"../images/social/social_ios_icon.png\"></a> </li>\n";
echo "        </ul>\n";
echo "    </div>\n";
echo "    <div class=\"fb\">\n";
echo "    <iframe src=\"http://www.facebook.com/plugins/like.php?href=https://www.facebook.com/meglimited&amp;layout=button_count&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp\" style=\"overflow:hidden;width:100px;height:25px;\" scrolling=\"no\" frameborder=\"0\" allowTransparency=\"true\"></iframe>\n";
echo "    </div>\n";
echo "    \n";
echo "    \n";
echo "	\n";
echo "	<div id=\"lang_area\" class=\"dropdown_trigger_box\">\n";
echo "			<a href=\"javascript:void(0);\" class=\"bt_lang dropdown_trigger button\">\n";
echo "				<span>繁中</span>\n";
echo "				\n";
echo "			</a>\n";
echo "		\n";
echo "		<div class=\"dropdown\"><div class=\"lang_dd_header\"><div class=\"lang_dd_footer\"><div class=\"lang_dd_body\">\n";
echo "		<ul class=\"pt2\">\n";
echo "		\n";
echo "			<li>\n";
echo "				<a href=\"javascript:location.reload()\">\n";
echo "					<span>繁中</span>\n";
echo "					\n";
echo "				</a>\n";
echo "			</li>\n";
echo "		\n";
echo "			<li>\n";
echo "				<a class=\"sc\">\n";
echo "					<span>簡中</span>\n";
echo "					\n";
echo "				</a>\n";
echo "			</li>\n";
echo "		\n";
echo "			<li>\n";
echo "				<a class=\"eng\">\n";
echo "					<span>English</span>\n";
echo "					\n";
echo "				</a>\n";
echo "			</li>\n";
echo "	\n";
echo "		\n";
echo "		</ul>\n";
echo "		</div></div></div></div>\n";
echo "	</div>\n";
echo "    \n";
echo "	<div class=\"top_btn\">\n";
echo "    	<ul>\n";
echo "        <!--li><a id=\"cart\"><img src=\"../images/cart_icon.png\"><span>購物車</span></a></li-->\n";
echo "        <li><a id=\"price\"><img src=\"../images/price_icon.png\"><span>價格比較</span></a></li>\n";
echo "        </ul>\n";
echo "    </div>\n";
echo "    <div class=\"clearfix\"></div>\n";
echo "</div></div>\n";
echo "<!-- contents -->\n";
echo "<div id=\"player-over\">\n";
echo "	<!--<div id=\"player-black\"></div>-->\n";
echo "	\n";
echo "	<div id=\"top\" class=\"scroll_manage\">\n";
echo "		<h1 id=\"meg-title\" class=\"meg-logo\"></h1>\n";
echo "		<nav id=\"global_nav-top\">\n";
echo "			<ul>\n";
echo "				<li class=\"about\">\n";
echo "					<a href=\"#about_area\">\n";
echo "						<img src=\"../images/globalnav_top_01.png\" alt=\"about\"><img src=\"../images/globalnav_top_01_over.png\" alt=\"\" class=\"over\">\n";
echo "					</a>\n";
echo "					<ul>\n";
echo "						<li class=\"sub_navi_01\">\n";
echo "							<a href=\"#about_area\">\n";
echo "								<img src=\"./images/globalnav_top_01_sub_01.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"sub_navi_02\">\n";
echo "							<a href=\"latest_news.html\">\n";
echo "								<img src=\"./images/globalnav_top_01_sub_02.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "					</ul>\n";
echo "				</li>\n";
echo "				<li class=\"course\">\n";
echo "					<a href=\"#course_area\">\n";
echo "						<img src=\"../images/globalnav_top_02.png\" alt=\"course\"><img src=\"../images/globalnav_top_02_over.png\" alt=\"\" class=\"over\">\n";
echo "					</a>\n";
echo "					<ul>\n";
echo "						<li class=\"sub_navi_01\">\n";
echo "							<a href=\"#course__01\">\n";
echo "								<img src=\"./images/globalnav_top_02_sub_01.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"sub_navi_02\">\n";
echo "							<a href=\"#course__02\">\n";
echo "								<img src=\"./images/globalnav_top_02_sub_02.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"sub_navi_03\">\n";
echo "							<a href=\"#course__03\">\n";
echo "								<img src=\"./images/globalnav_top_02_sub_03.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"sub_navi_04\">\n";
echo "							<a href=\"#course__04\">\n";
echo "								<img src=\"./images/globalnav_top_02_sub_04.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"sub_navi_05\">\n";
echo "							<a href=\"#course__05\">\n";
echo "								<img src=\"./images/globalnav_top_02_sub_05.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "					</ul>\n";
echo "				</li>\n";
echo "				<li class=\"info\">\n";
echo "					<a href=\"#info_area\">\n";
echo "						<img src=\"../images/globalnav_top_03.png\" alt=\"info\"><img src=\"../images/globalnav_top_03_over.png\" alt=\"\" class=\"over\">\n";
echo "					</a>\n";
echo "					<ul>\n";
echo "						<li class=\"sub_navi_01\">\n";
echo "							<a href=\"#info__01\">\n";
echo "								<img src=\"./images/globalnav_top_03_sub_01.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"sub_navi_02\">\n";
echo "							<a href=\"#info__02\">\n";
echo "								<img src=\"./images/globalnav_top_03_sub_02.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"sub_navi_03\">\n";
echo "							<a href=\"#info__03\">\n";
echo "								<img src=\"./images/globalnav_top_03_sub_03.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "                        <li class=\"sub_navi_04\">\n";
echo "							<a href=\"#info__04\">\n";
echo "								<img src=\"./images/globalnav_top_03_sub_04.png\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "					</ul>\n";
echo "				</li>\n";
echo "				<li class=\"contact\">\n";
echo "					<a href=\"#contact_area\">\n";
echo "						<img src=\"../images/globalnav_top_04.png\" alt=\"contact\"><img src=\"../images/globalnav_top_04_over.png\" alt=\"\" class=\"over\">\n";
echo "					</a>\n";
echo "				</li>\n";
echo "			</ul>\n";
echo "		</nav>\n";
echo "<!--notice_area-->       \n";
echo "	<div id=\"notice_area\">\n";
echo "        <div id=\"notice_area__inner\" class=\"clearfix\">\n";
echo "        	<div class=\"latest_news\">\n";
echo "        	<iframe src=\"./scroll_headline.html\" width=\"100%\" height=\"100%\"  frameborder=\"0\" scrolling=\"no\" allowtransparency=\"true\"></iframe>\n";
echo "            <a id=\"latest_news\" class=\"more\">+MORE</a>\n";
echo "            <div class=\"clearfix\"></div>\n";
echo "            </div>\n";
echo "            \n";
echo "        </div>\n";
echo "    </div>\n";
echo "	\n";
echo "        \n";
echo "<!--banner_area-->       \n";
echo "	<div id=\"banner_area\">\n";
echo "        <div id=\"banner_area__inner\" class=\"clearfix\">\n";
echo "            <iframe src=\"./banner.html\" width=\"100%\" height=\"100%\"  frameborder=\"0\" scrolling=\"no\" allowtransparency=\"true\"></iframe>         \n";
echo "		</div>\n";
echo "	</div>\n";
echo "    \n";
echo "<!--logo_area-->\n";
echo "		<div id=\"logo_area\"><div id=\"logo_area__inner\" class=\"clearfix\">\n";
echo "			<div class=\"col--left\">\n";
echo "            	<div class=\"logo_button\"><a id=\"hksm_s\"><img src=\"../images/hksm_logo_s.png\" alt=\"\"></a></div>\n";
echo "            </div>\n";
echo "            <!--div class=\"col--left\">\n";
echo "            	<div class=\"logo_button\"><a id=\"freeway_s\"><img src=\"../images/freeway_logo_s.png\" alt=\"\"></a></div>\n";
echo "            </div-->\n";
echo "            <div class=\"col--left\">\n";
echo "            	<div class=\"logo_button\"><a id=\"A1_s\"><img src=\"../images/a1_logo_s.png\" alt=\"\"></a></div>\n";
echo "            </div>\n";
echo "            <div class=\"col--left last\">\n";
echo "            	<div class=\"logo_button\"><a id=\"enquiry\"><img src=\"./images/enquiry.png\" alt=\"\"></a></div>\n";
echo "            </div>\n";
echo "            <div class=\"clearfix\"></div>\n";
echo "        </div></div>    \n";
echo "    \n";
echo "<!--other_area-->\n";
echo "		<div id=\"other_area\">\n";
echo "			<div id=\"other_area__inner\" class=\"clearfix\">\n";
echo "				<div class=\"col--left\">\n";
echo "					<div class=\"trailer\">\n";
echo "								<img src=\"../images/trailer_icon_4.jpg\" class=\"trailer__thumb\">\n";
echo "								<a class=\"video trailer__button\" href=\"https://www.youtube.com/watch?v=LOvay2DZ_W8?start=0&end=177&amp;autoplay=1\">\n";
echo "								<div class=\"inner\">\n";
echo "									<img src=\"../images/trailer_button.png\" alt=\"\" class=\"normal\">\n";
echo "									<img src=\"../images/trailer_button_over.png\" alt=\"\" class=\"over\">\n";
echo "								</div>\n";
echo "								</a>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "				<div class=\"col--right\">\n";
echo "					<div class=\"row clearfix\">\n";
echo "						<div class=\"mb4\">\n";
echo "							<a id=\"promotion1\">\n";
echo "								<img src=\"../images/banner/banner_2.jpg\" alt=\"\" class=\"border over1\">\n";
echo "							</a>\n";
echo "						</div>\n";
echo "						<div class=\"col--left\">\n";
echo "							<a id=\"promotion2\"><img src=\"./images/banner/banner_2.gif\" alt=\"\" class=\"border over1\"></a>\n";
echo "						</div>\n";
echo "						<div class=\"col--right\">\n";
echo "							<a id=\"notices\"><img src=\"./images/banner/banner_3.gif\" alt=\"\" class=\"border over1\"></a>\n";
echo "						</div>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "</div>\n";
echo "<!-- //#player-over -->\n";
echo "<div id=\"contents\" class=\"scroll_manage\">\n";
echo "	<header id=\"header-conts\">\n";
echo "		<div id=\"global_nav-conts\">\n";
echo "			<nav class=\"nav\">\n";
echo "				<div class=\"nav__inner\">\n";
echo "					<h1 class=\"logo\">\n";
echo "						<a href=\"#top\">\n";
echo "							\n";
echo "								<img src=\"../images/logo_1.png\" alt=\"\">\n";
echo "							\n";
echo "						</a>\n";
echo "					</h1>\n";
echo "					\n";
echo "					<ul>\n";
echo "						<li class=\"about\">\n";
echo "							<a href=\"#about_area\">\n";
echo "								<img src=\"../images/globalnav_conts_01.png\" alt=\"ABOUT\"><img src=\"../images/globalnav_conts_01_over.png\" alt=\"\" class=\"over\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"course\">\n";
echo "							<a href=\"#course_area\">\n";
echo "								<img src=\"../images/globalnav_conts_02.png\" alt=\"course\"><img src=\"../images/globalnav_conts_02_over.png\" alt=\"\" class=\"over\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"info\">\n";
echo "							<a href=\"#info_area\">\n";
echo "								<img src=\"../images/globalnav_conts_03.png\" alt=\"info\"><img src=\"../images/globalnav_conts_03_over.png\" alt=\"\" class=\"over\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "						<li class=\"contact\">\n";
echo "							<a href=\"#contact_area\">\n";
echo "								<img src=\"../images/globalnav_conts_04.png\" alt=\"contact\"><img src=\"../images/globalnav_conts_04_over.png\" alt=\"\" class=\"over\">\n";
echo "							</a>\n";
echo "						</li>\n";
echo "					</ul>\n";
echo "					<div class=\"indicate\"><img src=\"../images/globalnav_conts_indicate.png\"></div>\n";
echo "				</div>\n";
echo "			</nav>\n";
echo "			<nav class=\"subnav\">\n";
echo "				<div class=\"subnav__inner\">\n";
echo "					<ul class=\"course\">\n";
echo "						<li><a href=\"#course__01\">私家車課程</a></li>\n";
echo "						<li><a href=\"#course__02\">輕型貨車課程</a></li>\n";
echo "						<li><a href=\"#course__03\">電單車課程</a></li>\n";
echo "						<li><a href=\"#course__04\">的士課程</a></li>\n";
echo "						<li class=\"last\"><a href=\"#course__05\">商業車輛課程</a></li>\n";
echo "					</ul>\n";
echo "					<ul class=\"info\">\n";
echo "						<li><a href=\"#info__01\">課程比較</a></li>\n";
echo "						<li><a href=\"#info__02\">模擬筆試</a></li>\n";
echo "                        <li><a href=\"#info__03\">學車及考試流程</a></li>\n";
echo "						<li class=\"last\"><a href=\"#info__04\">考試路線</a></li>\n";
echo "					</ul>\n";
echo "				</div>\n";
echo "			</nav>\n";
echo "		</div>\n";
echo "	</header>\n";
echo "	<!-- //header -->\n";
echo "	<!-- about -->\n";
echo "	<div id=\"about_area\" class=\"scroll_manage\">\n";
echo "	<section id=\"about__main\" class=\"conts scroll_manage\">\n";
echo "	<div class=\"conts__inner\">\n";
echo "		<nav class=\"conts_nav clearfix\">\n";
echo "			<h1>\n";
echo "				<img src=\"../images/about_title.png\"><br>\n";
echo "				<img src=\"./images/about_title_sub01.png\">\n";
echo "			</h1>\n";
echo "		</nav>\n";
echo "		<div class=\"view\">\n";
echo "			\n";
echo "			<div id=\"about__main-content\">\n";
echo "				<div class=\"image_01\"><img src=\"../images/about_img01.png\"></div>\n";
echo "				<div class=\"text_01\">\n";
echo "                	<p class=\"notices_title\">MEG一站式學車顧問</p>\n";
echo "                    	<div class=\"sub_content\">\n";
echo "                    		<p class=\"info2\">MEG (Motoring Excellence Group) 於2010年成立，屬於一所以全新概念提供學車資訊和駕駛課程顧問的服務平台，我們是香港駕駛學院及A1駕駛學校兩間不同駕駛學校的獨家代理，以切合您的預算及需要，為您提供不同學車課程選擇。<br /><br />\n";
echo "我們抱著提供優質服務的信念，致力為您提供多元化的學車課程資訊及專業意見。<br /><br />\n";
echo "我們的使命是搜羅市面上最新的學車優惠及資訊，幫助您選擇合適的駕駛課程，節省您搜尋資訊的時間，讓您享受和體驗真正的學車樂趣，成功考取車牌。</p>\n";
echo "                    	</div>\n";
echo "                </div>\n";
echo "                <div class=\"btn\">\n";
echo "                    		<ul>\n";
echo "                    		<li><a id=\"hksm_logo\"><img src=\"../images/hksm_btn.png\"></a></li>\n";
echo "                            <!--li><a id=\"freeway_logo\"><img src=\"../images/freeway_btn.png\"></a></li-->\n";
echo "                            <li class=\"last\"><a id=\"A1_logo\"><img src=\"../images/a1_btn.png\"></a></li>\n";
echo "                       	 	</ul>\n";
echo "                    </div>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "	</section>\n";
echo "	</div>\n";
echo "	<!-- end of about-->\n";
echo "    \n";
echo "    \n";
echo "	<!-- course -->\n";
echo "	<div id=\"course_area\" class=\"scroll_manage\">\n";
echo "    	<!-- course01 -->\n";
echo "		<section id=\"course__01\" class=\"conts scroll_manage\">\n";
echo "			<div class=\"conts__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/course_title.png\"><br>\n";
echo "					<img src=\"./images/course_title_sub01.png\">\n";
echo "				</h1>\n";
echo "			</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"course__01-content\">\n";
echo "					<div class=\"image_01\"><img src=\"../images/course_img01.png\"></div>\n";
echo "					<div class=\"text_01\">\n";
echo "                    	<div class=\"sub_content\">\n";
echo "                    		<p class=\"info2\">私家車課程包括理論(只適用於香港駕駛學院課程)與路面實習課，課程內容針對運輸署駕駛考試為主，讓學員清楚了解考試路線及掌握考試要點，增加學員駕駛考試合格的機會。<br /><br />\n";
echo "由於私家車體積較小而且相對容易操控，適合初學者或將來以駕駛一般家庭車輛為主的人士學習。<br /><br />\n";
echo "完成駕駛考試後便可申領暫准駕駛執照 <br />\n";
echo "(俗稱「P」牌)。</p>\n";
echo "                    	</div>\n";
echo "                    </div>\n";
echo "                    <div class=\"btn\">\n";
echo "                    	<ul>\n";
echo "                        	<li><a href=\"http://www.meghongkong.com/meg/index.php/app/index/HKSM_PC\" target=\"_blank\"><img src=\"./images/join_btn.png\" ></a></li>\n";
echo "                        </ul>\n";
echo "                    </div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "		</section>\n";
echo "        \n";
echo "        <!-- course02 -->\n";
echo "		<section id=\"course__02\" class=\"conts scroll_manage\">\n";
echo "			<div class=\"conts__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/course_title.png\"><br>\n";
echo "					<img src=\"./images/course_title_sub02.png\">\n";
echo "				</h1>\n";
echo "			</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"course__02-content\">\n";
echo "					<div class=\"image_01\"><img src=\"../images/course_img02.png\"></div>\n";
echo "					<div class=\"text_01\">\n";
echo "                    	<div class=\"sub_content\">\n";
echo "                    		<p class=\"info2\">輕型貨車車課程包括理論(只適用於香港駕駛學院課程)與路面實習課，課程內容針對運輸署駕駛考試要點，讓學員有充分準備應付駕駛考試。<br /><br />\n";
echo "駕駛棍波輕型貨車需要掌握波段及離合器的控制，一般較受愛好駕駛不同種類車輛人士歡迎或需要以駕駛作為職業的人士學習。駕駛考試合格後可同時加簽私家車駕駛執照，即考一個牌，便可擁有兩個牌(輕型貨車及私家車)，一舉兩得，省時方便。<br /><br />\n";
echo "香港駕駛學院最近引入新款自動波輕型貨車車款，以滿足一班既想學習駕駛輕型貨車又要學習自動波的人士。</p>\n";
echo "                    	</div>\n";
echo "                    </div>\n";
echo "                    <div class=\"btn\">\n";
echo "                    	<ul>\n";
echo "                        	<li><a href=\"http://www.meghongkong.com/meg/index.php/app/index/HKSM_LGV\" target=\"_blank\"><img src=\"./images/join_btn.png\"></a></li>\n";
echo "                        </ul>\n";
echo "                    </div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "		</section>\n";
echo "        \n";
echo "        <!-- course03 -->\n";
echo "		<section id=\"course__03\" class=\"conts scroll_manage\">\n";
echo "			<div class=\"conts__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/course_title.png\"><br>\n";
echo "					<img src=\"./images/course_title_sub03.png\">\n";
echo "				</h1>\n";
echo "			</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"course__03-content\">\n";
echo "					<div class=\"image_01\"><img src=\"../images/course_img03.png\"></div>\n";
echo "					<div class=\"text_01\">\n";
echo "                    <div class=\"sub_content\">\n";
echo "                    		<p class=\"info2\">學習駕駛電單車是年青人學習駕駛私家車和輕型貨車以外之選，因只要年滿十八歲便可報讀，而且一輛電單車的入門售價不高，學費亦相對私家車及輕型貨車便宜，是不少年青人選擇學習電單車作為代步工具。<br /><br/>\n";
echo "電單車課程分為棍波及自動波兩類。根據運輸署規定，所有報讀電單車課程的學員需要先進行「強制試」課程及考試，成功通過「強制試」後方可進行路面駕駛訓練及考試。完成路面駕駛考試後便可申領暫准駕駛執照 (俗稱「P」牌)。</p>\n";
echo "                    	</div>\n";
echo "                    </div>\n";
echo "                    <div class=\"btn\">\n";
echo "                    	<ul>\n";
echo "                        	<li><a href=\"http://www.meghongkong.com/meg/index.php/app/index/HKSM_MC\" target=\"_blank\"><img src=\"./images/join_btn.png\"></a></li>\n";
echo "                        </ul>\n";
echo "                    </div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "		</section>\n";
echo "        \n";
echo "        <!-- course04 -->\n";
echo "		<section id=\"course__04\" class=\"conts scroll_manage\">\n";
echo "			<div class=\"conts__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/course_title.png\"><br>\n";
echo "					<img src=\"./images/course_title_sub04.png\">\n";
echo "				</h1>\n";
echo "			</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"course__04-content\">\n";
echo "					<div class=\"image_01\"><img src=\"../images/course_img04.png\"></div>\n";
echo "					<div class=\"text_01\">\n";
echo "                    <div class=\"sub_content\">\n";
echo "                    		<p class=\"info2\">凡持有私家車／輕型貨車駕駛執照三年或以上之人士，均可報考的士駕駛執照考試。考試以選擇題形式進行，內容包括「的士則例」、「地方試題」及「道路使用者守則」。<br /><br />\n";
echo "考試要求三部份同時合格，才可獲發執照，可謂既容易又難的考試。<br />\n";
echo "<br />\n";
echo "有意報讀人士歡迎到各MEG門市查詢及報名。</p>\n";
echo "                    	</div>\n";
echo "                    </div>\n";
echo "                    <div class=\"btn\">\n";
echo "                    	<ul>\n";
echo "                        	<li><a href=\"http://www.meg.com.hk/images/timetable/TAXI_201702-201703.pdf\" target=\"_blank\"><img src=\"./images/taxi_timetable_btn.png\"></a></li>\n";
echo "                        </ul>\n";
echo "                    </div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "		</section>\n";
echo "		<!-- course05 -->\n";
echo "		<section id=\"course__05\" class=\"conts scroll_manage\">\n";
echo "			<div class=\"conts__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/course_title.png\"><br>\n";
echo "					<img src=\"./images/course_title_sub05.png\">\n";
echo "				</h1>\n";
echo "			</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"course__05-content\">\n";
echo "					<div class=\"image_01\"><img src=\"../images/course_img05.png\"></div>\n";
echo "					<div class=\"text_01\">\n";
echo "                    <div class=\"sub_content\">\n";
echo "                    		<p class=\"info2\">商業車輛課程分別包括中型貨車課程、巴士課程及掛接車課程。持有私家車或輕型貨車駕駛執照三年或以上及駕駛紀錄良好的人士，可報讀中型貨車課程及巴士課程；有意報讀掛接車課程人士則需持有中型貨車駕駛執照。<br /><br />\n";
echo "有關商業車輛課程的內容及詳情，請到各MEG門市或點擊以下連結查詢。</p>\n";
echo "                    	</div>\n";
echo "                    </div>\n";
echo "                    <div class=\"btn\">\n";
echo "                    	<ul>\n";
echo "                        	<li><a href=\"http://www.hksm.com.hk/tc/medium-goods-vehicle.html\" target=\"_blank\"><img src=\"./images/course_btn01.png\"></a></li>\n";
echo "                            <li><a href=\"http://www.hksm.com.hk/tc/bus.html\" target=\"_blank\"><img src=\"./images/course_btn02.png\"></a></li>\n";
echo "                            <li><a href=\"http://www.hksm.com.hk/tc/articulated-vehicle.html\" target=\"_blank\"><img src=\"./images/course_btn03.png\"></a></li>\n";
echo "                        </ul>\n";
echo "                    </div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "		</section>\n";
echo "	</div>\n";
echo "    <!-- end of course-->\n";
echo "	<!-- info -->\n";
echo "	<div id=\"info_area\" class=\"scroll_manage\">\n";
echo "    \n";
echo "    <!-- info01 -->\n";
echo "		<section id=\"info__01\" class=\"conts scroll_manage\">\n";
echo "			<div class=\"conts__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/info_title.png\"><br>\n";
echo "					<img src=\"./images/info_title_sub01.png\">\n";
echo "				</h1>\n";
echo "			</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"info__01-content\">\n";
echo "					<div class=\"image_01\">\n";
echo "                    	<div class=\"container\">\n";
echo "        <iframe src=\"./info_1.html\" width=\"100%\" height=\"100%\"  frameborder=\"0\" scrolling=\"no\" allowtransparency=\"true\"></iframe>\n";
echo "                   		</div>\n";
echo "                    </div>\n";
echo "					\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "		</section>\n";
echo "        \n";
echo "	<!-- info02 -->\n";
echo "		<section id=\"info__02\" class=\"conts scroll_manage\">\n";
echo "			<div class=\"conts__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/info_title.png\"><br>\n";
echo "					<img src=\"./images/info_title_sub02.png\">\n";
echo "				</h1>\n";
echo "			</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"info__02-content\">\n";
echo "					<div class=\"text_01\">有膽量挑戰一下自己對駕駛<br>或道路安全的各項知識?</div>\n";
echo "                    <div class=\"text_02\">按下面按鈕測試自己的實力吧！</div>\n";
echo "                    <div class=\"btn\"><a class=\"iframe\" href=\"http://www.meghongkong.com/parta_new/index.php\">按此進入</a></div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "		</section>\n";
echo "        \n";
echo "	<!-- info03 -->\n";
echo "		<section id=\"info__03\" class=\"conts scroll_manage\">\n";
echo "			<div class=\"conts__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/info_title.png\"><br>\n";
echo "					<img src=\"./images/info_title_sub03.png\">\n";
echo "				</h1>\n";
echo "			</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"info__03-content\">\n";
echo "					<div class=\"image_01\">私家車及輕型貨車<br><img src=\"./images/info/exam_flow_01.jpg\"></div>\n";
echo "					<div class=\"image_02\">電單車<br><img src=\"./images/info/exam_flow_02.jpg\"></div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "		</section>		\n";
echo "	<!-- info04 -->\n";
echo "		<section id=\"info__04\" class=\"conts scroll_manage\">\n";
echo "			<div class=\"conts__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/info_title.png\"><br>\n";
echo "					<img src=\"./images/info_title_sub04.png\">\n";
echo "				</h1>\n";
echo "			</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"info__04-content\">\n";
echo "					<div class=\"image_01\">\n";
echo "                    <p>按下地點可觀看地圖</p>\n";
echo "  <p><img src=\"./images/info/exam_route.jpg\" usemap=\"#Map\" border=\"0\" class=\"img_round_corner\" />\n";
echo "    <map name=\"Map\" id=\"Map\">\n";
echo "      <area shape=\"rect\" coords=\"17,12,126,70\" href=\"http://www.hksm.com.hk/tc/exam-route_3.html\" target=\"_blank\" alt=\"元朗\" />\n";
echo "      <area shape=\"rect\" coords=\"282,528,390,587\" href=\"http://www.hksm.com.hk/tc/exam-route_2.html\" target=\"_blank\" alt=\"鴨脷洲\" />\n";
echo "      <area shape=\"rect\" coords=\"228,151,337,210\" id=\"fancybox-R\" href=\"javascript:;\" alt=\"石蔭\" />\n";
echo "      <area shape=\"rect\" coords=\"399,165,508,221\" id=\"fancybox-B\" href=\"javascript:;\" alt=\"澤安道\" />\n";
echo "      <area shape=\"rect\" coords=\"312,277,422,337\" id=\"fancybox-P\" href=\"javascript:;\" alt=\"培正道\" />\n";
echo "      <area shape=\"rect\" coords=\"454,349,564,407\" id=\"fancybox-TT\" href=\"javascript:;\" alt=\"忠義街\" />\n";
echo "      <area shape=\"rect\" coords=\"377,441,486,500\" id=\"fancybox-H\" href=\"javascript:;\" alt=\"跑馬地\" />\n";
echo "      <area shape=\"rect\" coords=\"648,386,758,444\" id=\"fancybox-S\" href=\"javascript:;\" alt=\"油塘\" />\n";
echo "      <area shape=\"rect\" coords=\"540,227,649,286\" id=\"fancybox-T\" href=\"javascript:;\" alt=\"天光道\" />\n";
echo "      <area shape=\"rect\" coords=\"577,141,686,198\" href=\"http://www.hksm.com.hk/tc/exam-route.html\" target=\"_blank\" alt=\"沙田\" />\n";
echo "      <area shape=\"rect\" coords=\"559,440,653,489\" id=\"fancybox-SK\" href=\"javascript:;\" alt=\"掃桿埔\" />\n";
echo "    </map>\n";
echo "  </p>\n";
echo "  <p>註1: 以下的考試路線及地點只供參考，運輸署有權隨時更改考試路線及地點而不會預先作出通知。 <br />\n";
echo "    註2: 橙色地點為香港駕駛學院專屬考線 </p></div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "		</section>	\n";
echo "		\n";
echo "	</div>\n";
echo "    <!-- end of info -->\n";
echo "	<!-- contact -->\n";
echo "	<div id=\"contact_area\" class=\"scroll_manage\">\n";
echo "	<section id=\"contact__main\" class=\"conts scroll_manage\">\n";
echo "	<div class=\"conts__inner\">\n";
echo "		<nav class=\"conts_nav clearfix\">\n";
echo "			<h1>\n";
echo "				<img src=\"../images/contact_title.png\"><br>\n";
echo "				<img src=\"./images/contact_title_sub01.png\">\n";
echo "			</h1>\n";
echo "		</nav>\n";
echo "		<div class=\"view\">\n";
echo "			\n";
echo "			<div id=\"contact__main-content\">\n";
echo "				<div class=\"image_01\">\n";
echo "                	<div class=\"container\">\n";
echo "                <iframe src=\"./contact.html\" width=\"100%\" height=\"100%\"  frameborder=\"0\" scrolling=\"no\" allowtransparency=\"true\"></iframe>\n";
echo "                	</div>\n";
echo "                </div>\n";
echo "				\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "	</section>\n";
echo "	</div>\n";
echo "	<!-- end of contact-->\n";
echo "    \n";
echo "    \n";
echo "    <!-- partner -->\n";
echo "	\n";
echo "    \n";
echo "    <!-- info01 -->\n";
echo "		<div id=\"partner_area\" class=\"scroll_manage\">\n";
echo "			<div id=\"partner__inner\">\n";
echo "				<nav class=\"conts_nav clearfix\">\n";
echo "				<h1>\n";
echo "					<img src=\"../images/partner_title.png\"><br>\n";
echo "					<img src=\"./images/partner_title_sub01.png\">\n";
echo "				</h1>\n";
echo "				</nav>\n";
echo "			<div class=\"view\">\n";
echo "			\n";
echo "				<div id=\"partner__main-content\">\n";
echo "					<div class=\"image_01\">\n";
echo "                    	    <a id=\"hksm\"><img src=\"../images/cooperation/co_001.png\"></a>\n";
echo "                            <!--a id=\"freeway\"><img src=\"../images/cooperation/co_002.png\"></a-->\n";
echo "                            <a id=\"A1\"><img src=\"../images/cooperation/co_003.png\"></a>\n";
echo "                            <a id=\"leinam\"><img src=\"../images/cooperation/co_007.png\"></a>\n";
echo "                            <a id=\"tctc\"><img src=\"../images/cooperation/co_005.png\"></a>\n";
echo "                            <a id=\"autotoll\"><img src=\"../images/cooperation/co_004.png\"></a>\n";
echo "                    </div>\n";
echo "					\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			</div>\n";
echo "        </div>\n";
echo "	<!-- end of partner-->\n";
echo "    \n";
echo "</div>\n";
echo "<!-- pagetop -->\n";
echo "<div class=\"bt_pagetop\"></div>\n";
echo "<!-- //pagetop -->\n";
echo "<!-- footer -->\n";
echo "<footer id=\"footer\">\n";
echo "	<div class=\"inner\">\n";
echo "    	<div class=\"bottom_btn\">\n";
echo "		<ul class=\"menu\">\n";
echo "			<li class=\"privacy_policy\"><a id=\"terms\" alt=\"私隱政策\">私隱政策</a></li>\n";
echo "            <li class=\"support_center\"><a id=\"enquiry\" alt=\"網上查詢\">網上查詢</a></li>\n";
echo "		</ul>\n";
echo "        </div>\n";
echo "		<div class=\"copy mb5\" id=\"meg_copy\"></p>\n";
echo "        \n";
echo "	</div>\n";
echo "	<div class=\"clearfix\"></div>\n";
echo "</footer>\n";
echo "<!-- //footer -->\n";
echo "<!-- js-->\n";
echo "<script src=\"../js/jquery-1.8.3.min.js\"></script>\n";
echo "<script src=\"../js/jquery.easing.1.3.js\"></script>\n";
echo "<script src=\"../js/jquery.fn.js\"></script>\n";
echo "<script src=\"../js/fn.js\"></script>\n";
echo "<script src=\"../js/lodestone.js\"></script>\n";
echo "<script src=\"../js/meg.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"../js/exam_route.js\"></script>\n";
echo "<script src=\"../js/tab_script.js\"></script> \n";
echo "<script src=\"../js/nav_link.js\"></script> \n";
echo "<!--fancybox-->\n";
echo "<!-- Add jQuery library -->\n";
echo "	<!script type=\"text/javascript\" src=\"../fancyBox/lib/jquery-1.10.1.min.js\"></script>\n";
echo "	<!-- Add mousewheel plugin (this is optional) -->\n";
echo "	<script type=\"text/javascript\" src=\"../fancyBox/lib/jquery.mousewheel-3.0.6.pack.js\"></script>\n";
echo "	<!-- Add fancyBox main JS and CSS files -->\n";
echo "	<script type=\"text/javascript\" src=\"../fancyBox/source/jquery.fancybox.js?v=2.1.5\"></script>\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"../fancyBox/source/jquery.fancybox.css?v=2.1.5\" media=\"screen\" />\n";
echo "	<!-- Add Button helper (this is optional) -->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"../fancyBox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5\" />\n";
echo "	<script type=\"text/javascript\" src=\"../fancyBox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5\"></script>\n";
echo "	<!-- Add Thumbnail helper (this is optional) -->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"../fancyBox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7\" />\n";
echo "	<script type=\"text/javascript\" src=\"../fancyBox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7\"></script>\n";
echo "	<!-- Add Media helper (this is optional) -->\n";
echo "	<script type=\"text/javascript\" src=\"../fancyBox/source/helpers/jquery.fancybox-media.js?v=1.0.6\"></script>\n";
echo "    \n";
echo "<script type=\"text/javascript\">\n";
echo "jQuery(document).ready(function() {\n";
echo "	$(\".iframe\").fancybox({\n";
echo "	\'width\'         : \'780\',\n";
echo "    \'height\'        : \'450\',\n";
echo "    \'autoScale\'     : false,\n";
echo "    \'transitionIn\'  : \'none\',\n";
echo "    \'transitionOut\' : \'none\',\n";
echo "    \'type\'          : \'iframe\',\n";
echo "	\'fitToView\' 	: false,\n";
echo "	\'iframe\': {\'scrolling\': \'no\'},\n";
echo "	helpers: {\n";
echo "    overlay: {\n";
echo "      locked: false,\n";
echo "    }\n";
echo "  }\n";
echo "});\n";
echo "	$(\".video\").click(function() {\n";
echo "		$.fancybox({\n";
echo "			\'padding\'		: 0,\n";
echo "			\'autoScale\'		: false,\n";
echo "			\'width\'     : 800,\n";
echo "			\'height\'    : 450,\n";
echo "			\'transitionIn\'	: \'none\',\n";
echo "			\'transitionOut\'	: \'none\',\n";
echo "			\'title\'			: this.title,\n";
echo "			\'href\'			: this.href.replace(new RegExp(\"watch\\\\?v=\", \"i\"), \'v/\'),\n";
echo "			\'type\'			: \'swf\',\n";
echo "			\'swf\'			: {\n";
echo "			\'wmode\'				: \'transparent\',\n";
echo "			\'allowfullscreen\'	: \'true\'\n";
echo "			}\n";
echo "		});\n";
echo "		return false;\n";
echo "	});\n";
echo "});\n";
echo "</script>\n";
echo "<!-- google Analytics -->\n";
echo "<script>\n";
echo "		(function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){\n";
echo "			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n";
echo "			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n";
echo "		})(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');\n";
echo "		ga(\'create\', \'UA-78524347-1\', \'auto\');\n";
echo "		ga(\'send\', \'pageview\');\n";
echo "	</script>\n";
echo "<!-- //js-->\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
?>